# name: Deploy Angular Application

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy:
#     runs-on: self-hosted 
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '21.6.2'
#     - name: Install client dependencies
#       run: |
#           cd jpstats-client
#           npm i
#     - name: Build client
#       run: |
#           cd jpstats-client
#           npm run build -- --pro
#     - name: Deploy Build to Serving Directory
#       run: |
#         rm -rf /var/www/html/* 
#         cp -R jpstats-client/build/* /var/www/html/
